# Generated by Django 5.2.4 on 2025-11-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupstation',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=10),
        ),
    ]
